language: node_js
node_js:
  - "8"

before_install:
  - sudo apt-get update

install:
  - sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose --version

script:
  # Build project.
  - docker-compose pull
  - docker-compose build
  # Lint project.
  - npm install --prefix app --only=dev
  - npm run --prefix app lint